{
"quartz": {
  "msg": {
    "config": {
      "mr_enclave": "44eebb5bb9838a31751442552a676a2e3b087003798c4efc124bf98ccd38e003",
      "epoch_duration": {
        "secs": 43200,
        "nanos": 0
      },
      "light_client_opts": {
        "chain_id": "testing",
        "trusted_height": 1,
        "trusted_hash": "2ef0e6f9bddf5deaa6fcd6492c3db26d7c62bffc01b538a958d04376e0b67185",
        "trust_threshold": [
          2,
          3
        ],
        "trusting_period": 1209600,
        "max_clock_drift": 5,
        "max_block_lag": 5
      }
    }
  },
  "attestation": {
    "report": {
      "report": {
        "id": "53035249646140512286779050465788497169",
        "timestamp": "2024-06-18T17:59:19.533781",
        "version": 4,
        "epidPseudonym": "+CUyIi74LPqS6M0NF7YrSxLqPdX3MKs6D6LIPqRG/ZEB4WmxZVvxAJwdwg/0m9cYnUUQguLnJotthX645lAogfJgO8Xg5/91lSegwyUKvHmKgtjOHX/YTbVe/wmgWiBdaL+KmarY0Je459Px/FqGLWLsAF7egPAJRd1Xn88Znrs=",
        "advisoryURL": "https://security-center.intel.com",
        "advisoryIDs": [
          "INTEL-SA-00161",
          "INTEL-SA-00219",
          "INTEL-SA-00289",
          "INTEL-SA-00334",
          "INTEL-SA-00615"
        ],
        "isvEnclaveQuoteStatus": "CONFIGURATION_AND_SW_HARDENING_NEEDED",
        "platformInfoBlob": "150200650000080000141402040180070000000000000000000D00000C000000020000000000000CB0BB04DD814D97659EBFDB3D5FBBCB44D543DC69D99D40350B387241F8178D08E07ACB0BDFED808DEA8774275484B0D13176783FD261424598BEF8CCAAD0E71AC9",
        "isvEnclaveQuoteBody": "AgABALAMAAAPAA8AAAAAAFHK9aSLRQ1iSu/jKG0xSJQAAAAAAAAAAAAAAAAAAAAAFBQCBwGAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABQAAAAAAAAAHAAAAAAAAAETuu1u5g4oxdRRCVSpnai47CHADeYxO/BJL+YzNOOADAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABoFidqz5zgbbpRc84G6XMGkx1yMVbl/pI4vgPwipAuggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+B8dfkZeoVV1pivY6A16F1AFAXxSN98drREuEzZEJegAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
      },
      "reportsig": "MAUhVswA0P8C5xKS0sSpukjsyxBZ8Q7vgyY23ThpDLmzL9sdUgFDm2RmzlmydVWF7cygjC9Xe4iH1ghZjppT02zpyejV/7itxtSuxDcbnCIHrC3GWYe8YLu+CdJvZTeysfcR+7j1p53/MtSjxC7aU+bzIqKPssZlEw0C3Eww6v6Sql9Q+nlqrwho7GlEkuvnbATMhwOMRfNqIkJvny9LKG6rJpvyMZ1b+Sr8vkOkrmK06WHbMgWrp8tNWrDN/gwtcucoSVbJWUfVsbrl8TVIA0Z/47TVv2QTCMhFG+b9b7Antla0Bt3kamu6GgB55dZvGzFtJmXXZo/Ax6gi4B9uJg=="
    }
  }
},
"denom": "ucosm"
}
