import { routes } from '@/config/routes'
import test from './fixtures'

test.describe('Log in', () => {
  test('log in to the app successfully', async ({ context, page }) => {
    await page.goto(routes.landing)
    await page.getByRole('button', { name: /connect/i }).click()

    // Accept app suggested testnet info
    const addChainPage = await context.waitForEvent('page')

    await addChainPage.getByRole('button', { name: /approve/i }).click()
    await addChainPage.waitForEvent('close')

    // Accept autogenerated seed phrase
    await page.getByRole('button', { name: /continue with/i }).click()
    await test.expect(page.getByText(/balance:/i)).toBeVisible()
  })
})
