mock_sgx = true
tx_sender = "admin"
chain_id = "testing"
node_url = "http://127.0.0.1:26657"
ws_url = "ws://127.0.0.1:26657/websocket"
grpc_url = "http://127.0.0.1:9090"
enclave_rpc_addr = "http://127.0.0.1"
enclave_rpc_port = 11090
trusted_hash = ""
trusted_height = 0
release = true