namespace NodeJS {
  interface ProcessEnv {
    NEXT_PUBLIC_ENCLAVE_PUBLIC_KEY: string
    NEXT_PUBLIC_TARGET_CHAIN: string
    NEXT_PUBLIC_TRANSFERS_CONTRACT_ADDRESS: string
    TEST_BASE_URL: string
    TEST_KEPLR_EXTENSION_VERSION: string
    TEST_WALLET_MNEMONIC: string
    TEST_SECONDARY_WALLET_MNEMONIC: string
    TEST_SECONDARY_WALLET_ADDRESS: string
    TEST_WALLET_PASSWORD: string
  }
}
