[workspace]

[package]
name = "ping-pong-contract"
version = "0.2.0"
edition = "2021"
authors = ["Informal Systems <hello@informal.systems>"]
exclude = ["contract.wasm", "hash.txt"]

[[bin]]
name = "schema"
path = "bin/schema.rs"

[lib]
crate-type = ["cdylib", "rlib"]

[profile.release]
opt-level = "z"
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true

[features]
mock-sgx = ["quartz-contract-core/mock-sgx"]
library = []

[dependencies]
# external
serde_json = { version = "1.0.122", default-features = false }
thiserror = { version = "1.0.63" }

# cosmwasm
cosmwasm-std = { version = "2.1.1", default-features = false, features = [
  "abort", "iterator"
] }
cosmwasm-schema = { version = "2.1.1", default-features = false }
cw-storage-plus = { version = "2.0.0", default-features = false, features = ["iterator"] }
cw-utils = { version = "2.0.0", default-features = false }

# quartz
quartz-contract-core = { path = "../../../crates/contracts/core" }
quartz-contract-core-derive = { path = "../../../crates/contracts/core/derive" }

# patch indirect deps
getrandom = { version = "0.2.15", features = ["js"] }

[dev-dependencies]
cw-multi-test = { version = "2.1.0", default-features = false }
serde_json = "1.0.122"
